---
title: "LiteratureOverview"
author: "Chris Cox"
date: "2025-12-19"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bibliometrix Overview

```{r}
pacman::p_load(bibliometrix,
               tidyverse,
               Matrix,
               igraph,
               here)

#import data
citations <- convert2df('~/Library/CloudStorage/OneDrive-Aarhusuniversitet/Skrivebord/NonHumanVocalExchanges/articles.bib', dbsource = "wos")
try <- read.csv('~/Library/CloudStorage/OneDrive-Aarhusuniversitet/Skrivebord/NonHumanVocalExchanges/articles.csv')
glimpse(try)


# clean article names
for (i in seq(length(citations$SR))){
  from <- str_split(citations$SR[i],",")[[1]]
  citations$SR[i] <- paste0(str_split(from," ")[[1]][1],from[2])
  citations$SR_FULL[i] <- paste0(str_split(from," ")[[1]][1],from[2])
}

#summary results
results <- biblioAnalysis(citations, sep = ";")
S=summary(object = results, pause = FALSE)

# Traditional network analysis of the papers:
NetMatrix <- biblioNetwork(citations, analysis = "coupling", network = "references", sep = ". ")

a <- dimnames(NetMatrix)
b <- unlist(a[[1]])

c <- sapply(strsplit(b, " "), `[`,1)
d <- sapply(strsplit(b, " "), `[`,3)

e <- str_c(c, ", ", d)

e[15] <- "KLANN-DELIUS, 1997"
dimnames(NetMatrix) <- list(e, e)

#Plot the network:
net2 <- networkPlot(NetMatrix, 
                    normalize = "association", 
                    n = 26, 
                    Title = "",
                    size=27, 
                    labelsize = 1.1,
                    label.color = "black",
                    cluster = "louvain",
                    label.cex = F,
                    type = "fruchterman", 
                    remove.multiple=FALSE, 
                    halo = F,
                    edgesize = 3,
                    curved = F,
                    alpha = 0.9,
                    size.cex = TRUE)
title("Coupling Network for Studies on Infant Turn-Taking",cex.main=3,col.main="black")

#Citation network
dCit <- citations
edges <- NULL

for (i in seq(length(dCit))){
  
  from <- dCit$SR[i]
  
  x <- str_split(dCit$CR[i], pattern = ";")[[1]]
  
  for (k in seq(length(x))){
    
    to <- str_split(x[k], ",")[[1]]
    to <- paste0(str_split(trimws(to[1], "l")," ")[[1]][1],to[2])
    
    temp <- tibble(from = from, to = to)
    
    if(exists("edges")){edges <- rbind(edges,temp)} else {edges <- temp}
    
  }
  
}

edges <- edges %>% subset(!is.na(from))
nodes <- tibble(id = unique(c(edges$from)))
edges <- edges %>% subset(!is.na(to))

to <- unique(edges$to[edges$to %in% edges$from])

edges <- edges %>% subset(to %in% from) 

net <- graph_from_data_frame(d=edges, vertices=nodes, directed=FALSE)
net <- simplify(net, remove.multiple = FALSE, remove.loops = TRUE) 
colrs <- c("blue", "tomato", "gold", "purple", "green")
#V(net)$color <- colrs[V(net)$symptom.type]
#EdgeColor <- ifelse(E(net)$weight > 0, "blue","red")
#E(net)$color <- ifelse(E(net)$weight > 0, "blue","red")
#E(net)$weight <- abs(E(net)$weight)
#E(net)$width <- abs(E(net)$weight)*6

# Community detection (by optimizing modularity over partitions):
clp <- cluster_louvain(net)
#clp <- optimal.community(net)
a <- plot(clp, net, 
     vertex.frame.color = "#ffffff",
     vertex.label.color = "black", 
     vertex.label.font = 0.1,
     edge.curved = .2)
title("Direct-Citation Network for Studies on Infant Turn-Taking",cex.main=3,col.main="Black")


```

